FROM golang:alpine AS build-env
RUN apk --no-cache add git protobuf make
RUN go get github.com/golang/protobuf/protoc-gen-go
ADD . /src
RUN cd /src && make -C api/example/v1

FROM envoyproxy/envoy-alpine:latest
COPY --from=build-env src/api/example/v1/example.proto-descriptor /etc/example.proto-descriptor
